package com.myallways.vwru2.hibernate.maps;

import java.sql.Timestamp;

/**
 * generated by hibernate tools comment:系统用户主表
 */
public class SysUser {

	/**
	 * 用户ID,唯一标识<seq:seq_ru_sys_user>
	 */
	private Long nuserid;
	/**
	 * 用户名
	 */
	private String vusername;
	/**
	 * 密码
	 */
	private String vpassword;
	/**
	 * 雇员名称
	 */
	private String vempname;
	/**
	 * 帐号状态:1:有效,0:无效,2:被禁用
	 */
	private String vstatus;
	/**
	 * 创建人
	 */
	private String vcreated;
	/**
	 * 创建日期
	 */
	private Timestamp dcrtDate;
	/**
	 * 更新人
	 */
	private String vupdated;
	/**
	 * 更新日期
	 */
	private Timestamp dupDate;

	/**
	 * generate default constructor for SysUser
	 */
	public SysUser() {
	}

	/**
	 * 设置用户ID,唯一标识<seq:seq_ru_sys_user>
	 */
	public void setNuserid(Long nuserid) {
		this.nuserid = nuserid;
	}

	/**
	 * 获取用户ID,唯一标识<seq:seq_ru_sys_user>
	 */
	public Long getNuserid() {
		return this.nuserid;
	}

	/**
	 * 设置用户名
	 */
	public void setVusername(String vusername) {
		this.vusername = vusername;
	}

	/**
	 * 获取用户名
	 */
	public String getVusername() {
		return this.vusername;
	}

	/**
	 * 设置密码
	 */
	public void setVpassword(String vpassword) {
		this.vpassword = vpassword;
	}

	/**
	 * 获取密码
	 */
	public String getVpassword() {
		return this.vpassword;
	}

	/**
	 * 设置雇员名称
	 */
	public void setVempname(String vempname) {
		this.vempname = vempname;
	}

	/**
	 * 获取雇员名称
	 */
	public String getVempname() {
		return this.vempname;
	}

	/**
	 * 设置帐号状态:1:有效,0:无效,2:被禁用
	 */
	public void setVstatus(String vstatus) {
		this.vstatus = vstatus;
	}

	/**
	 * 获取帐号状态:1:有效,0:无效,2:被禁用
	 */
	public String getVstatus() {
		return this.vstatus;
	}

	/**
	 * 设置创建人
	 */
	public void setVcreated(String vcreated) {
		this.vcreated = vcreated;
	}

	/**
	 * 获取创建人
	 */
	public String getVcreated() {
		return this.vcreated;
	}

	/**
	 * 设置创建日期
	 */
	public void setDcrtDate(Timestamp dcrtDate) {
		this.dcrtDate = dcrtDate;
	}

	/**
	 * 获取创建日期
	 */
	public Timestamp getDcrtDate() {
		return this.dcrtDate;
	}

	/**
	 * 设置更新人
	 */
	public void setVupdated(String vupdated) {
		this.vupdated = vupdated;
	}

	/**
	 * 获取更新人
	 */
	public String getVupdated() {
		return this.vupdated;
	}

	/**
	 * 设置更新日期
	 */
	public void setDupDate(Timestamp dupDate) {
		this.dupDate = dupDate;
	}

	/**
	 * 获取更新日期
	 */
	public Timestamp getDupDate() {
		return this.dupDate;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@")
				.append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("nuserid").append("='").append(getNuserid()).append("' ");
		buffer.append("vusername").append("='").append(getVusername())
				.append("' ");
		buffer.append("vpassword").append("='").append(getVpassword())
				.append("' ");
		buffer.append("vempname").append("='").append(getVempname())
				.append("' ");
		buffer.append("vstatus").append("='").append(getVstatus()).append("' ");
		buffer.append("vcreated").append("='").append(getVcreated())
				.append("' ");
		buffer.append("dcrtDate").append("='").append(getDcrtDate())
				.append("' ");
		buffer.append("vupdated").append("='").append(getVupdated())
				.append("' ");
		buffer.append("dupDate").append("='").append(getDupDate()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysUser))
			return false;
		SysUser castOther = (SysUser) other;
		if (nuserid == null) {
			if (castOther.nuserid != null)
				return false;
		} else if (!nuserid.equals(castOther.nuserid))
			return false;
		if (vusername == null) {
			if (castOther.vusername != null)
				return false;
		} else if (!vusername.equals(castOther.vusername))
			return false;
		if (vpassword == null) {
			if (castOther.vpassword != null)
				return false;
		} else if (!vpassword.equals(castOther.vpassword))
			return false;
		if (vempname == null) {
			if (castOther.vempname != null)
				return false;
		} else if (!vempname.equals(castOther.vempname))
			return false;
		if (vstatus == null) {
			if (castOther.vstatus != null)
				return false;
		} else if (!vstatus.equals(castOther.vstatus))
			return false;
		if (vcreated == null) {
			if (castOther.vcreated != null)
				return false;
		} else if (!vcreated.equals(castOther.vcreated))
			return false;
		if (dcrtDate == null) {
			if (castOther.dcrtDate != null)
				return false;
		} else if (!dcrtDate.equals(castOther.dcrtDate))
			return false;
		if (vupdated == null) {
			if (castOther.vupdated != null)
				return false;
		} else if (!vupdated.equals(castOther.vupdated))
			return false;
		if (dupDate == null) {
			if (castOther.dupDate != null)
				return false;
		} else if (!dupDate.equals(castOther.dupDate))
			return false;
		return true;
	}

	public int hashCode() {
		final int prime = 31;
		int result = 17;
		result = prime * result + ((nuserid == null) ? 0 : nuserid.hashCode());
		result = prime * result
				+ ((vusername == null) ? 0 : vusername.hashCode());
		result = prime * result
				+ ((vpassword == null) ? 0 : vpassword.hashCode());
		result = prime * result
				+ ((vempname == null) ? 0 : vempname.hashCode());
		result = prime * result + ((vstatus == null) ? 0 : vstatus.hashCode());
		result = prime * result
				+ ((vcreated == null) ? 0 : vcreated.hashCode());
		result = prime * result
				+ ((dcrtDate == null) ? 0 : dcrtDate.hashCode());
		result = prime * result
				+ ((vupdated == null) ? 0 : vupdated.hashCode());
		result = prime * result + ((dupDate == null) ? 0 : dupDate.hashCode());
		return result;
	}
}
