/**
	generated by hibernate tools
<#if entity.hasDeclarationDoc()> 	comment:${entity.getDeclarationDoc()}</#if> 
*/
${entity.getClassModifiers()} ${entity.getDeclarationType()} ${entity.getDeclarationName()} ${entity.getExtendsDeclaration()} ${entity.getImplementsDeclaration()}